name: Publish to PyPI
on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install package
      run: |
          pip install build poetry

    - name: Build source tarball
      run: |
          rm -rf dist;
          poetry build
 
    - name: Publish distribution to Test PyPI
      uses: JRubics/poetry-publish@v1.17
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        repository_name: "testpypi"
        repository_url: "https://test.pypi.org/legacy/"
        #user: __token__
        #password: ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: JRubics/poetry-publish@v1.17
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        repository_name: "pypi"
        repository_url: "https://pypi.org/legacy/"
        #user: __token__
        #password: ${{ secrets.PYPI_API_TOKEN }}
